version: "3.3"

services:
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: 'no' #always
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    container_name: django
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    command: python manage.py runsslserver 0.0.0.0:8000
    command: gunicorn wpa_project.wsgi:application --bind 0.0.0.0:8000 --workers=4
#    command: ls
#    volumes:
#      - ./wpa_project:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - staticfiles:/home/app/web/staticfiles

  nginx:
    container_name: nginx
#    build: ./nginx
    image: nginx:mainline-alpine
    restart: 'no' #always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  postgres-data:
  staticfiles:
