version: "3.3"

services:
#  db:
##    image: postgres
##    environment:
##      - POSTGRES_DB=postgres
##      - POSTGRES_USER=postgres
##      - POSTGRES_PASSWORD=postgres
#    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
#    volumes:
#      - ./mysql:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: Mob6ymP9PK2rDrzFHL8j
#      MYSQL_USER: tester
#      MYSQL_PASSWORD: Plus6494
#    ports:
#      - 3306:3306
#    expose:
#      # Opens port 3306 on the container
#      - 3306

  web:
    build: .
    command: python manage.py test
    volumes:
      - ./wpa_project:/code
    ports:
      - 8000:8000
#    depends_on:
#      - db

