# Generated by Django 3.2.4 on 2022-01-05 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
