# Generated by Django 4.0.5 on 2022-09-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_spamwords_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_spam',
            field=models.BooleanField(default=True),
        ),
    ]
