# Generated by Django 4.0.5 on 2022-09-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_message_is_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='spam_category',
            field=models.CharField(choices=[('legit', 'legit'), ('undetermined', 'undetermined'), ('spam', 'spam')], default='undetermined', max_length=20),
        ),
    ]
