# Generated by Django 4.0.5 on 2022-10-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0006_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
