# Generated by Django 4.0.5 on 2022-10-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0008_blockeddomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='ip',
            field=models.GenericIPAddressField(default=None, null=True),
        ),
    ]
