# Generated by Django 5.2 on 2025-06-18 18:18

from django.db import migrations, models

def update_email(apps, schema_editor):
    # copy the event data from the beginner class table to the event table
    category = apps.get_model('contact_us', 'Category')

    for c in category.objects.all():
        c.email = c.recipients.first().email
        c.save()
    #

class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0011_complaintcomment_user_alter_complaint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(update_email),
        migrations.RemoveField(
            model_name='category',
            name='recipients',
        ),
    ]
