# Generated by Django 5.0.7 on 2025-03-25 00:36

from django.db import migrations, models

def create_policy(apps, schema_editor):
    # copy the event data from the beginner class table to the event table
    policy = apps.get_model('info', 'Policy')
    policy_text = apps.get_model('info', 'PolicyText')

    if not policy.objects.all().count():
        p = policy.objects.create(title="Range Rules")
        policy_text.objects.create(
            status=1,
            policy='rules',
            title=p
        )


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_policy_policytext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish'), (2, 'Obsolete')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_html', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=40)),
            ],
        ),
        migrations.RunPython(create_policy),
    ]
