# Generated by Django 5.0.7 on 2025-03-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_article_articlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ManyToManyField(to='info.articlepage'),
        ),
    ]
