# Generated by Django 5.2 on 2025-06-28 03:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_policy_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policytext',
            name='policy',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
