# Generated by Django 3.2.4 on 2022-01-16 20:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0010_student_is_joad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=120)),
                ('start_date', models.DateField(default=None, null=True)),
                ('state', models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('full', 'full'), ('closed', 'closed'), ('canceled', 'canceled'), ('recorded', 'recorded')], max_length=20, null=True)),
                ('student_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_status', models.CharField(max_length=20)),
                ('idempotency_key', models.UUIDField()),
                ('reg_time', models.DateField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='joad.session')),
                ('student', models.ForeignKey(limit_choices_to={'is_joad': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='JoadClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateTimeField()),
                ('state', models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('full', 'full'), ('closed', 'closed'), ('canceled', 'canceled'), ('recorded', 'recorded')], max_length=20, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='joad.session')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('joad_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='joad.joadclass')),
                ('student', models.ForeignKey(limit_choices_to={'is_joad': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.student')),
            ],
        ),
    ]
