# Generated by Django 3.2.4 on 2022-01-28 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_student_is_joad'),
        ('joad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=15)),
                ('event_date', models.DateTimeField(default=None, null=True)),
                ('event_type', models.CharField(choices=[('Pin Shoot', 'Pin Shoot')], max_length=40, null=True)),
                ('state', models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('full', 'full'), ('closed', 'closed'), ('canceled', 'canceled'), ('recorded', 'recorded')], max_length=20, null=True)),
                ('student_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PinScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bow', models.CharField(choices=[('barebow', 'Barebow/Basic Compound/Traditional'), ('olympic', 'Olympic Recurve'), ('compound', 'Compound')], max_length=45)),
                ('category', models.CharField(choices=[('joad_indoor', 'JOAD Indoor')], max_length=20)),
                ('distance', models.IntegerField(choices=[(9, 9), (18, 18)])),
                ('target', models.IntegerField(choices=[(40, 40), (60, 60), (80, 80), (122, 122)])),
                ('score', models.IntegerField()),
                ('stars', models.IntegerField(verbose_name=[(1, '1, Green'), (2, '2, Purple'), (3, '3, Grey'), (4, '4, White'), (5, '5, Black'), (6, '6, Blue'), (7, '7, Red'), (8, '8, Yellow'), (9, '9, Bronze'), (10, '10, Silver'), (11, '11, Gold')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='joadclass',
            name='state',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('past', 'past'), ('canceled', 'canceled')], default='scheduled', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PinAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bow', models.CharField(choices=[('barebow', 'Barebow/Basic Compound/Traditional'), ('olympic', 'Olympic Recurve'), ('compound', 'Compound')], max_length=45)),
                ('category', models.CharField(choices=[('joad_indoor', 'JOAD Indoor')], max_length=20)),
                ('distance', models.IntegerField(choices=[(9, 9), (18, 18)])),
                ('target', models.IntegerField(choices=[(40, 40), (60, 60), (80, 80), (122, 122)])),
                ('score', models.IntegerField()),
                ('stars', models.IntegerField(verbose_name=[(1, '1, Green'), (2, '2, Purple'), (3, '3, Grey'), (4, '4, White'), (5, '5, Black'), (6, '6, Blue'), (7, '7, Red'), (8, '8, Yellow'), (9, '9, Bronze'), (10, '10, Silver'), (11, '11, Gold')])),
                ('attended', models.BooleanField(default=False)),
                ('previous_stars', models.IntegerField(verbose_name=[(1, '1, Green'), (2, '2, Purple'), (3, '3, Grey'), (4, '4, White'), (5, '5, Black'), (6, '6, Blue'), (7, '7, Red'), (8, '8, Yellow'), (9, '9, Bronze'), (10, '10, Silver'), (11, '11, Gold')])),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='joad.joadevent')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_status', models.CharField(max_length=20)),
                ('idempotency_key', models.UUIDField()),
                ('reg_time', models.DateField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='joad.joadevent')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.student')),
            ],
        ),
    ]
