# Generated by Django 3.2.4 on 2022-01-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joad', '0002_auto_20220128_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinattendance',
            name='inner_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pinscores',
            name='inner_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='joadevent',
            name='event_type',
            field=models.CharField(choices=[('Pin Shoot', 'Pin Shoot')], default=('Pin Shoot', 'Pin Shoot'), max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='joadevent',
            name='state',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('full', 'full'), ('closed', 'closed'), ('canceled', 'canceled'), ('recorded', 'recorded')], default='open', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='joadevent',
            name='student_limit',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='pinattendance',
            name='bow',
            field=models.CharField(choices=[('barebow', 'Barebow/Basic Compound'), ('olympic', 'Recurve/Para Recurve Open'), ('compound', 'Compound/Para Compound Open/W1/Fixed Pins**')], max_length=45),
        ),
        migrations.AlterField(
            model_name='pinscores',
            name='bow',
            field=models.CharField(choices=[('barebow', 'Barebow/Basic Compound'), ('olympic', 'Recurve/Para Recurve Open'), ('compound', 'Compound/Para Compound Open/W1/Fixed Pins**')], max_length=45),
        ),
    ]
