# Generated by Django 3.2.4 on 2022-01-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joad', '0003_auto_20220128_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinattendance',
            name='category',
            field=models.CharField(choices=[('joad_indoor', 'JOAD Indoor')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinattendance',
            name='distance',
            field=models.IntegerField(choices=[(9, 9), (18, 18)], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pinattendance',
            name='previous_stars',
            field=models.IntegerField(default=0, verbose_name=[(0, '0, None'), (1, '1, Green'), (2, '2, Purple'), (3, '3, Grey'), (4, '4, White'), (5, '5, Black'), (6, '6, Blue'), (7, '7, Red'), (8, '8, Yellow'), (9, '9, Bronze'), (10, '10, Silver'), (11, '11, Gold')]),
        ),
        migrations.AlterField(
            model_name='pinattendance',
            name='score',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pinattendance',
            name='stars',
            field=models.IntegerField(default=None, null=True, verbose_name=[(0, '0, None'), (1, '1, Green'), (2, '2, Purple'), (3, '3, Grey'), (4, '4, White'), (5, '5, Black'), (6, '6, Blue'), (7, '7, Red'), (8, '8, Yellow'), (9, '9, Bronze'), (10, '10, Silver'), (11, '11, Gold')]),
        ),
        migrations.AlterField(
            model_name='pinattendance',
            name='target',
            field=models.IntegerField(choices=[(40, 40), (60, 60), (80, 80), (122, 122)], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pinscores',
            name='category',
            field=models.CharField(choices=[('joad_indoor', 'JOAD Indoor')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pinscores',
            name='distance',
            field=models.IntegerField(choices=[(9, 9), (18, 18)], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pinscores',
            name='score',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pinscores',
            name='stars',
            field=models.IntegerField(default=None, null=True, verbose_name=[(0, '0, None'), (1, '1, Green'), (2, '2, Purple'), (3, '3, Grey'), (4, '4, White'), (5, '5, Black'), (6, '6, Blue'), (7, '7, Red'), (8, '8, Yellow'), (9, '9, Bronze'), (10, '10, Silver'), (11, '11, Gold')]),
        ),
        migrations.AlterField(
            model_name='pinscores',
            name='target',
            field=models.IntegerField(choices=[(40, 40), (60, 60), (80, 80), (122, 122)], default=None, null=True),
        ),
    ]
