# Generated by Django 3.2.4 on 2022-01-29 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joad', '0004_auto_20220129_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinattendance',
            name='award_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pinattendance',
            name='idempotency_key',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pinattendance',
            name='pay_status',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='reg_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='joadevent',
            name='event_type',
            field=models.CharField(choices=[('joad_indoor', 'JOAD Indoor'), ('other', 'Other')], default=('joad_indoor', 'JOAD Indoor'), max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pinattendance',
            name='distance',
            field=models.IntegerField(choices=[(None, None), (9, 9), (18, 18)], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pinattendance',
            name='target',
            field=models.IntegerField(choices=[(None, None), (40, 40), (60, 60), (80, 80), (122, 122)], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pinscores',
            name='distance',
            field=models.IntegerField(choices=[(None, None), (9, 9), (18, 18)], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pinscores',
            name='target',
            field=models.IntegerField(choices=[(None, None), (40, 40), (60, 60), (80, 80), (122, 122)], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reg_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
