# Generated by Django 3.2.4 on 2022-01-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joad', '0005_auto_20220129_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='joadevent',
            name='pin_cost',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
