# Generated by Django 4.0.5 on 2022-12-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_user_theme'),
        ('joad', '0009_remove_joadclass_class_date_remove_joadclass_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_joad': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_registration', to='student_app.student'),
        ),
    ]
