# Generated by Django 5.0.7 on 2025-02-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joad', '0011_auto_20221221_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinattendance',
            name='pay_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], default='card', max_length=20),
        ),
    ]
