# Generated by Django 5.2 on 2025-07-08 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_created=True)),
                ('bow_id', models.CharField(max_length=40)),
                ('hand', models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('A', 'Ambidextrous')], max_length=20)),
                ('poundage', models.IntegerField()),
                ('length', models.IntegerField()),
                ('type', models.CharField(choices=[('TDR', 'Take Down Recurve'), ('1PC', 'One Piece'), ('CPD', 'Compound')], max_length=10)),
                ('riser_material', models.CharField(choices=[('plastic', 'Plastic'), ('wood', 'Wood'), ('rubber', 'Rubber')], max_length=40)),
                ('riser_manufacturer', models.CharField(max_length=40)),
                ('riser_color', models.CharField(max_length=20)),
                ('limb_color', models.CharField(max_length=20)),
                ('limb_manufacturer', models.CharField(max_length=40)),
                ('limb_model', models.CharField(max_length=20)),
                ('in_service', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BowInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_date', models.DateTimeField(auto_now=True)),
                ('bow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
