# Generated by Django 5.2 on 2025-07-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bow',
            name='is_youth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bow',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bow',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
