from django.urls import path
from .views import *
app_name = 'registration'
urlpatterns = [
        path('', IndexView.as_view(), name='index'),
        path('add_student/<int:student_id>/', AddStudentView.as_view(), name='add_student'),
        path('add_student', AddStudentView.as_view(), name='add_student'),
        path('beginner_class/<int:beginner_class>/', BeginnerClassView.as_view(), name='beginner_class'),
        path('beginner_class', BeginnerClassView.as_view(), name='beginner_class'),
        path('class_status/<str:class_date>/', ClassStatusView.as_view(), name='class_status'),
        path('class_list', BeginnerClassListView.as_view(), name='class_list'),
        path('class_registered_table', ClassRegisteredTable.as_view(), name='class_registered_table'),
        path('class_registration/<int:reg_id>', ClassRegistrationView.as_view(), name='class_registration'),
        path('class_registration', ClassRegistrationView.as_view(), name='class_registration'),
        path('costs/<int:cost_id>', CostsView.as_view(), name='costs'),
        path('costs', CostsView.as_view(), name='costs'),
        path('payment', PaymentView.as_view(), name='payment'),
        path('process_payment', ProcessPaymentView.as_view(), name='process_payment'),
        path('process_payment/<str:message>/', ProcessPaymentView.as_view(), name='process_payment'),
        path('profile', ProfileView.as_view(), name='profile'),
        path('search', SearchView.as_view(), name='search'),
        path('student_api/<int:student_id>/', StudentApiView.as_view(), name='student_api'),
        path('student_api', StudentApiView.as_view(), name='student_api'),
        path('student_family_api/<int:family_id>/', StudentFamilyApiView.as_view(), name='student_family_api'),
        path('student_family_api', StudentFamilyApiView.as_view(), name='student_family_api'),
        path('student_list', StudentList.as_view(), name='student_list'),
        path('student_list_json', StudentListJson.as_view(), name='student_list_json'),
        path('student_register/<int:family_id>/', StudentFamilyRegisterView.as_view(), name='student_register'),
        path('student_register', StudentFamilyRegisterView.as_view(), name='student_register'),
        path('student_table', StudentTableView.as_view(), name='student_table'),
        path('theme', ThemeView.as_view(), name='theme'),
        path('unregister_class', UnregisterView.as_view(), name='unregister_class'),
]
