# Generated by Django 3.2.3 on 2021-05-28 17:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeginnerClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateField()),
                ('enrolled_beginners', models.IntegerField(default=0)),
                ('beginner_limit', models.IntegerField()),
                ('enrolled_returnee', models.IntegerField(default=0)),
                ('returnee_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=3)),
                ('post_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('email_verified', models.BooleanField(default=False)),
                ('registration_date', models.DateField(default=datetime.datetime(2021, 5, 28, 17, 58, 28, 362003, tzinfo=utc))),
                ('verification_code', models.CharField(max_length=50, null=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('login', models.BooleanField()),
                ('safety_class', models.DateField(null=True)),
                ('student_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.studentfamily')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_students', models.IntegerField()),
                ('pay_status', models.CharField(max_length=20)),
                ('idempotency_key', models.UUIDField(default='53b02bb0-1f8d-4378-8d25-8c80db211025')),
                ('beginner_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.beginnerclass')),
                ('student_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.student')),
            ],
        ),
    ]
