# Generated by Django 3.2.3 on 2021-05-28 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='login',
        ),
        migrations.RemoveField(
            model_name='studentfamily',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentfamily',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='studentfamily',
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='classregistration',
            name='idempotency_key',
            field=models.UUIDField(default='b1a1fe2d-cba0-4c35-ba79-f5cb32228e7c'),
        ),
        migrations.AlterField(
            model_name='studentfamily',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 28, 21, 57, 59, 959420, tzinfo=utc)),
        ),
    ]
