# Generated by Django 3.2.4 on 2021-09-12 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_family',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.studentfamily'),
        ),
    ]
