# Generated by Django 3.2.4 on 2021-10-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='covid_vax',
            field=models.BooleanField(default=False),
        ),
    ]
