# Generated by Django 3.2.4 on 2022-01-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0009_auto_20220109_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_joad',
            field=models.BooleanField(default=False),
        ),
    ]
