# Generated by Django 3.2.4 on 2022-04-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_student_is_joad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instructor_level',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
