# Generated by Django 4.0.5 on 2022-10-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0011_user_instructor_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('browser', 'browser'), ('dark', 'dark'), ('light', 'light')], default='browser', max_length=20),
        ),
    ]
