# Generated by Django 5.2 on 2025-06-30 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_user_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('board', 'For voting board members'), ('board_plus', 'For board members and previous President'), ('instructors', 'For our active instructors'), ('staff', 'for our staff'), ('members', 'For members')]},
        ),
    ]
