# Generated by Django 5.2 on 2025-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_user',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
