version: "3.7"
services:
  sftp:
    image: "emberstack/sftp"
    ports:
      - "22:22"
    volumes:
      - ./sftp.json:/app/config/sftp.json:ro
      - ../wordpress:/home/wp-user

networks:
  default:
    name: my-app-net
    external: true