# Generated by Django 3.2.4 on 2022-04-02 18:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0002_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutes',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='minutes',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='business',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='businessupdate',
            name='update_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='meeting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
