# Generated by Django 3.2.4 on 2022-04-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0003_auto_20220402_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
