# Generated by Django 3.2.4 on 2022-04-02 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0004_minutes_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='resolved',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='businessupdate',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='decision_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
