# Generated by Django 4.0.5 on 2022-08-06 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0005_auto_20220402_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='businessupdate',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
