# Generated by Django 4.0.5 on 2022-09-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0006_alter_business_added_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='minutes',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minutes.minutes'),
        ),
    ]
