# Generated by Django 4.2.6 on 2023-10-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0007_decision_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='balance',
            field=models.FloatField(default=None, null=True),
        ),
    ]
