# Generated by Django 4.2.6 on 2024-01-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0008_alter_minutes_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutes',
            name='reimbursement_review',
            field=models.BooleanField(default=False),
        ),
    ]
