# Generated by Django 5.0.7 on 2025-02-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0009_minutes_reimbursement_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='owner',
            field=models.CharField(choices=[('president', 'President'), ('vice', 'Vice'), ('secretary', 'Secretary'), ('treasure', 'Treasure'), ('webmaster', 'Webmaster')], max_length=50),
        ),
    ]
