# Generated by Django 5.2 on 2025-05-12 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

def insert_poll_choices(apps, schema_editor):
    # insert common poll choices.
    ep = apps.get_model('minutes', 'PollChoices')
    choices = ['Aye', 'Nay', 'Abstain', 'Yes', 'No']
    for c in choices:
        ep.objects.create(choice=c)

class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0010_alter_report_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_motion', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=300)),
                ('level', models.CharField(choices=[('board', 'board'), ('staff', 'staff'), ('members', 'members')], max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('closed', 'closed')], max_length=20, null=True)),
                ('duration', models.IntegerField(default=1)),
                ('business', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minutes.business')),
                ('minutes', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minutes.minutes')),
                ('poll_choices', models.ManyToManyField(to='minutes.pollchoices')),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minutes.poll')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(insert_poll_choices),
    ]
