# Generated by Django 5.2 on 2025-05-14 20:33

import django.db.models.deletion
import minutes.models.poll_model
from django.db import migrations, models

def insert_poll_type(apps, schema_editor):
    # insert common poll choices.
    ep = apps.get_model('minutes', 'PollType')
    pt = ['motion']
    for c in pt:
        ep.objects.create(poll_type=c)

class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0011_pollchoices_poll_pollvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_type', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='is_motion',
        ),
        migrations.AlterField(
            model_name='poll',
            name='level',
            field=models.CharField(choices=[('board', 'Board'), ('instructors', 'Instructors'), ('staff', 'Staff'), ('members', 'Members')], max_length=20),
        ),
        migrations.AlterField(
            model_name='poll',
            name='state',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('closed', 'closed'), ('canceled', 'canceled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pollchoices',
            name='choice',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_type',
            field=models.ForeignKey(default=minutes.models.poll_model.PollType.get_default_pk, on_delete=django.db.models.deletion.PROTECT, to='minutes.polltype'),
        ),
        migrations.RunPython(insert_poll_type),
    ]
