# Generated by Django 5.2 on 2025-05-15 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0012_polltype_remove_poll_is_motion_alter_poll_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollvote',
            old_name='election',
            new_name='poll',
        ),
        migrations.AddField(
            model_name='pollvote',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='minutes.pollchoices'),
            preserve_default=False,
        ),
    ]
