# Generated by Django 5.2 on 2025-05-17 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_alter_election_description_and_more'),
        ('minutes', '0013_rename_election_pollvote_poll_pollvote_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='discord_message',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='election',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.election'),
        ),
    ]
