# Generated by Django 5.2 on 2025-05-18 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.BigIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('board', 'Board'), ('instructors', 'Instructors'), ('staff', 'Staff'), ('members', 'Members')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordChannelRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=20)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discord_bot.discordchannel')),
            ],
        ),
    ]
