version: "3.7"

services:
  db:
    container_name: devdb
    image: postgres:latest
    restart: 'no' #always
    env_file:
      - ../wpa_project/wpa_project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    container_name: django_dev
    env_file:
          - ../wpa_project/wpa_project.env
    build:
      context: ..
      dockerfile: docker_development/Dockerfile
#    command: python manage.py runserver 0.0.0.0:8000
    command: python manage.py runsslserver 0.0.0.0:8000

    volumes:
      - ../wpa_project:/code
    ports:
      - 8000:8000
    depends_on:
      - db
#    env_file:
#      - ../wpa_project/wpa_project.env

networks:
  default:
    name: my-app-net
#    external: true

volumes:
  postgres-data:
  staticfiles:
