# Generated by Django 5.0.2 on 2024-03-24 22:07

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('to', models.IntegerField(default=0)),
                ('cc', models.IntegerField(default=0)),
                ('bcc', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BulkEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('sent_time', models.DateTimeField(default=None, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
