# Generated by Django 5.0.2 on 2024-03-25 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkemail',
            name='html',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='emailcounts',
            name='date',
            field=models.DateField(default=datetime.datetime.today, unique_for_date=True),
        ),
    ]
