# Generated by Django 3.2.4 on 2021-08-28 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('member_cost', models.IntegerField()),
                ('standard_cost', models.IntegerField()),
                ('membership', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RefundLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('created_time', models.DateTimeField()),
                ('location_id', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=192, null=True)),
                ('payment_id', models.CharField(max_length=192, null=True)),
                ('processing_fee', models.IntegerField(default=None, null=True)),
                ('refund_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_created_time', models.DateTimeField()),
                ('db_model', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('location_id', models.CharField(max_length=100, null=True)),
                ('idempotency_key', models.UUIDField()),
                ('payment_id', models.CharField(max_length=100, null=True)),
                ('order_id', models.CharField(max_length=100, null=True)),
                ('receipt', models.URLField(null=True)),
                ('source_type', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('total_money', models.IntegerField()),
                ('student_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.studentfamily')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
