# Generated by Django 3.2.4 on 2022-06-19 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_donationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlog',
            name='db_model',
        ),
        migrations.RemoveField(
            model_name='paymentlog',
            name='student_family',
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='donation',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('creation_source', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('version', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.IntegerField(default=None, null=True)),
                ('card_brand', models.CharField(max_length=20, null=True)),
                ('card_type', models.CharField(max_length=20, null=True)),
                ('card_id', models.CharField(max_length=50, null=True)),
                ('cardholder_name', models.CharField(max_length=100, null=True)),
                ('enabled', models.BooleanField()),
                ('exp_month', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('fingerprint', models.CharField(max_length=100, null=True)),
                ('last_4', models.IntegerField()),
                ('merchant_id', models.CharField(max_length=20, null=True)),
                ('prepaid_type', models.CharField(max_length=20, null=True)),
                ('version', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.customer')),
            ],
        ),
    ]
