# Generated by Django 4.0.5 on 2022-08-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_card_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenterrorlog',
            old_name='db_model',
            new_name='category',
        ),
        migrations.AddField(
            model_name='paymenterrorlog',
            name='api',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymenterrorlog',
            name='error_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
