# Generated by Django 4.0.5 on 2022-08-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_db_model_paymenterrorlog_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenterrorlog',
            name='idempotency_key',
            field=models.UUIDField(null=True),
        ),
    ]
