# Generated by Django 4.2.1 on 2023-07-09 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_reimbursement_reimbursementvote_reimbursementitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reimbursementvote',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
