# Generated by Django 5.0.7 on 2024-09-01 18:32

from django.db import migrations, models


def remove_duplicates(apps, schema_editor):
    # copy the event data from the beginner class table to the event table
    pl = apps.get_model('payment', 'PaymentLog')
    for row in pl.objects.all().order_by('id').reverse():
        if pl.objects.filter(idempotency_key=row.idempotency_key).count() > 1:
            row.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_reimbursement_note_alter_reimbursement_modified'),
    ]

    operations = [
        # migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE;'),
        migrations.RunPython(remove_duplicates),
        # migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED;'),
    ]
