# Generated by Django 5.0.7 on 2024-09-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_remove_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlog',
            name='idempotency_key',
            field=models.UUIDField(unique=True),
        ),
    ]
