# Generated by Django 5.2 on 2025-04-25 23:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_paymentlog_idempotency_key'),
        ('student_app', '0012_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(default=0)),
                ('collected_date', models.DateTimeField(default=datetime.datetime.now)),
                ('note', models.CharField(default=None, max_length=200, null=True)),
                ('board_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='student_app.student')),
                ('treasurer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='student_app.student')),
            ],
        ),
    ]
