# Generated by Django 5.2 on 2025-04-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='correction',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='collections',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
