# Generated by Django 4.0.5 on 2022-09-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=False)),
                ('fetched_time', models.DateTimeField()),
                ('is_live', models.BooleanField(default=False)),
                ('link', models.URLField(null=True)),
                ('post_id', models.PositiveBigIntegerField()),
                ('post_text', models.TextField()),
                ('post_url', models.URLField()),
                ('text', models.TextField()),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
    ]
