# Generated by Django 5.0.7 on 2024-07-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_embeddedposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='post_text',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='available',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='fetched_time',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='link',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='text',
        ),
        migrations.AddField(
            model_name='posts',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_id',
            field=models.CharField(max_length=100),
        ),
    ]
