# from .tests.tests_admit_wait import TestsAdmitWait
# from .tests.tests_beginner_class import TestsBeginnerClass
# from .tests.tests_beginner_class import TestsBeginnerClass2
# from .tests.tests_calendar import TestsCalendar
# from .tests.tests_class_attendance import TestsClassAttendance
# from .tests.tests_class_payment import TestsClassPayment
# from .tests.tests_class_registration import TestsClassRegistration
# from .tests.tests_class_registration_admin import TestsClassAdminRegistration
# from .tests.tests_class_registration_helper import TestsClassRegistrationHelper
# from .tests.tests_class_send_email import TestsClassSendEmail
# from .tests.tests_class_sign_in import TestsClassSignIn
# from .tests.tests_class_status import TestsClassStatus
# from .tests.tests_history import TestsAttendanceHistory
# from .tests.tests_logs import TestsAdminRegistration
# from .tests.tests_signal import TestsSignal
# from .tests.tests_staff_report import TestsStaffReport
# from .tests.tests_unregister import TestsUnregisterStudent
# from .tests.tests_unregister import TestsUnregisterStudent2
from .tests.tests_update_programs import TestsUpdatePrograms
# from .tests.tests_update_programs import TestsUpdatePrograms2
