# Generated by Django 3.2.4 on 2021-08-31 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('cost', models.IntegerField()),
                ('description', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
                ('min_age', models.IntegerField(default=None, null=True)),
                ('max_age', models.IntegerField(default=None, null=True)),
                ('is_family', models.BooleanField(default=False)),
                ('additional_cost', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('attending', models.CharField(max_length=250)),
                ('minutes_text', models.CharField(max_length=250)),
                ('memberships', models.IntegerField()),
                ('balance', models.IntegerField(default=None, null=True)),
                ('discussion', models.TextField()),
                ('end_time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinutesBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('business', models.TextField()),
                ('resolved', models.DateField(default=None, null=True)),
                ('minutes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.minutes')),
            ],
        ),
        migrations.CreateModel(
            name='MinutesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(choices=[('president', 'President'), ('vice', 'Vice'), ('secretary', 'Secretary'), ('treasure', 'Treasure')], max_length=50)),
                ('report', models.TextField()),
                ('minutes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.minutes')),
            ],
        ),
        migrations.CreateModel(
            name='MinutesBusinessUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('update_text', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.minutesbusiness')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('pay_status', models.CharField(max_length=20)),
                ('idempotency_key', models.UUIDField()),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.level')),
                ('students', models.ManyToManyField(to='student_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateField(default=django.utils.timezone.now)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_app.student')),
            ],
        ),
    ]
