# Generated by Django 3.2.4 on 2021-09-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutesbusiness',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='minutesbusinessupdate',
            name='business',
        ),
        migrations.RemoveField(
            model_name='minutesreport',
            name='minutes',
        ),
        migrations.DeleteModel(
            name='Minutes',
        ),
        migrations.DeleteModel(
            name='MinutesBusiness',
        ),
        migrations.DeleteModel(
            name='MinutesBusinessUpdate',
        ),
        migrations.DeleteModel(
            name='MinutesReport',
        ),
    ]
