# Generated by Django 4.0.5 on 2022-07-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20210905_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='begin_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
