# Generated by Django 4.0.5 on 2023-02-25 20:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_user_theme'),
        ('membership', '0003_member_begin_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, 'President'), (2, 'Vice President'), (3, 'Secretary'), (4, 'Treasurer'), (5, 'Member at Large')])),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.election')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_large', models.ManyToManyField(limit_choices_to={'position': 5}, related_name='at_large_candidate', to='membership.electioncandidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.election')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.member')),
                ('president', models.ForeignKey(limit_choices_to={'position': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='president_candidate', to='membership.electioncandidate')),
                ('secretary', models.ForeignKey(limit_choices_to={'position': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='secretary_candidate', to='membership.electioncandidate')),
                ('treasurer', models.ForeignKey(limit_choices_to={'position': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_candidate', to='membership.electioncandidate')),
                ('vice_president', models.ForeignKey(limit_choices_to={'position': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='vice_candidate', to='membership.electioncandidate')),
            ],
        ),
    ]
