# Generated by Django 4.0.5 on 2023-02-25 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_electionposition_election_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioncandidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.electionposition'),
        ),
    ]
