# Generated by Django 4.0.5 on 2023-02-26 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_alter_electioncandidate_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionvote',
            name='at_large',
        ),
        migrations.AddField(
            model_name='electionvote',
            name='member_at_large',
            field=models.ManyToManyField(limit_choices_to={'position': 5}, null=True, related_name='at_large_candidate', to='membership.electioncandidate'),
        ),
        migrations.AlterField(
            model_name='electionvote',
            name='president',
            field=models.ForeignKey(limit_choices_to={'position': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='president_candidate', to='membership.electioncandidate'),
        ),
        migrations.AlterField(
            model_name='electionvote',
            name='secretary',
            field=models.ForeignKey(limit_choices_to={'position': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretary_candidate', to='membership.electioncandidate'),
        ),
        migrations.AlterField(
            model_name='electionvote',
            name='treasurer',
            field=models.ForeignKey(limit_choices_to={'position': 4}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_candidate', to='membership.electioncandidate'),
        ),
        migrations.AlterField(
            model_name='electionvote',
            name='vice_president',
            field=models.ForeignKey(limit_choices_to={'position': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_candidate', to='membership.electioncandidate'),
        ),
    ]
