# from .tests.tests_attendance import TestsJoadAttendance
# from .tests.tests_class import TestsJoadClass
# from .tests.tests_class import TestsJoadClassList
# from .tests.tests_event import TestsJoadEvent
# from .tests.tests_event_attendance import TestsEventAttendance
# from .tests.tests_eventregistration import TestsJoadEventRegistration
# from .tests.tests_index import TestsJoadIndex
# from .tests.tests_other import TestsJoadOther
# from .tests.tests_pin_scores import TestsPinScores
# from .tests.tests_registration import TestsJoadRegistration
# from .tests.tests_registration_cancel import TestsJoadRegistrationCancel
# from .tests.tests_session import TestsJoadSession
# from .tests.tests_signal import TestsSignal
# from .tests.tests_waiver import TestsWaiver
