# Generated by Django 4.0.5 on 2022-11-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('cost_standard', models.IntegerField(default=0)),
                ('cost_member', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('wait', 'wait'), ('full', 'full'), ('closed', 'closed'), ('canceled', 'canceled'), ('recorded', 'recorded')], max_length=20, null=True)),
                ('volunteer_points', models.IntegerField(default=0)),
            ],
        ),
    ]
