# Generated by Django 4.0.5 on 2022-11-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('class', 'class'), ('joad', 'joad'), ('special', 'special'), ('work', 'work')], max_length=20, null=True),
        ),
    ]
