# Generated by Django 4.0.5 on 2022-12-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('class', 'class'), ('joad class', 'joad class'), ('joad event', 'joad event'), ('special', 'special'), ('work', 'work')], max_length=20, null=True),
        ),
    ]
