# Generated by Django 4.0.5 on 2022-12-08 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_user_theme'),
        ('event', '0003_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_points', models.IntegerField(default=0)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
            ],
        ),
    ]
