# Generated by Django 4.0.5 on 2022-12-11 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def copy_registration_data(apps, schema_editor):
    # copy the event data from the beginner class table to the event table
    cr = apps.get_model('program_app', 'ClassRegistration')
    er = apps.get_model('event', 'Registration')

    for c in cr.objects.all().order_by('id'):
        er.objects.create(
            pay_status=c.pay_status,
            idempotency_key=c.idempotency_key,
            reg_time=c.reg_time,
            attended=c.attended,
            modified=c.modified,
            event=c.beginner_class.event,
            student=c.student,
            user=c.user
        )

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_app', '0012_user_theme'),
        ('program_app', '0012_beginnerclass_event'),
        ('event', '0004_volunteerrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_status', models.CharField(choices=[('admin', 'admin'), ('canceled', 'canceled'), ('paid', 'paid'), ('refund', 'refund'), ('refund donated', 'refund donated'), ('refunded', 'refunded'), ('start', 'start')], max_length=20)),
                ('idempotency_key', models.UUIDField()),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.student')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_limit', models.IntegerField(default=20)),
                ('description', models.TextField()),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('class_registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.registration')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(copy_registration_data),
    ]
