# Generated by Django 4.0.5 on 2023-05-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_volunteerrecord_volunteer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='volunteer_heavy',
            field=models.BooleanField(default=False),
        ),
    ]
