# Generated by Django 4.0.5 on 2023-05-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_registration_volunteer_heavy'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='comment',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
