# Generated by Django 4.0.5 on 2023-05-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_registration_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='pay_status',
            field=models.CharField(choices=[('admin', 'admin'), ('canceled', 'canceled'), ('cancel_pending', 'cancel_pending'), ('paid', 'paid'), ('refund', 'refund'), ('refund donated', 'refund donated'), ('refunded', 'refunded'), ('start', 'start')], max_length=20),
        ),
    ]
