# Generated by Django 4.2.6 on 2023-10-27 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_user_theme'),
        ('event', '0009_alter_registration_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='pay_status',
            field=models.CharField(choices=[('admin', 'admin'), ('canceled', 'canceled'), ('paid', 'paid'), ('refund', 'refund'), ('refund donated', 'refund donated'), ('refunded', 'refunded'), ('start', 'start')], max_length=20),
        ),
        migrations.CreateModel(
            name='VolunteerAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(default=False)),
                ('award', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('events', models.ManyToManyField(to='event.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student')),
            ],
        ),
    ]
