# Generated by Django 4.2.6 on 2023-10-28 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0012_user_theme'),
        ('event', '0010_alter_registration_pay_status_volunteeraward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeraward',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.student'),
        ),
    ]
