# Generated by Django 4.2.6 on 2023-10-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_volunteeraward_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeraward',
            name='award_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
