# Generated by Django 3.2.4 on 2021-08-28 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeginnerClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_date', models.DateTimeField()),
                ('beginner_limit', models.IntegerField()),
                ('returnee_limit', models.IntegerField()),
                ('state', models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('full', 'full'), ('closed', 'closed'), ('canceled', 'canceled'), ('recorded', 'recorded')], max_length=20, null=True)),
                ('cost', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_student', models.BooleanField()),
                ('pay_status', models.CharField(max_length=20)),
                ('idempotency_key', models.UUIDField()),
                ('reg_time', models.DateField(default=django.utils.timezone.now)),
                ('attended', models.BooleanField(default=False)),
                ('signature', models.ImageField(null=True, upload_to='signatures/%Y/%m/%d/')),
                ('beginner_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='program_app.beginnerclass')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_app.student')),
            ],
        ),
    ]
