# Generated by Django 3.2.4 on 2021-10-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnerclass',
            name='instructor_limit',
            field=models.IntegerField(default=10),
        ),
    ]
