# Generated by Django 3.2.4 on 2021-10-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0002_beginnerclass_instructor_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnerclass',
            name='class_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beginnerclass',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
