# Generated by Django 3.2.4 on 2022-01-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0003_auto_20211031_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classregistration',
            name='signature',
        ),
        migrations.AlterField(
            model_name='beginnerclass',
            name='class_type',
            field=models.CharField(choices=[('beginner', 'beginner'), ('returnee', 'returnee'), ('combined', 'combined')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beginnerclass',
            name='state',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('full', 'full'), ('closed', 'closed'), ('canceled', 'canceled'), ('recorded', 'recorded')], max_length=20, null=True),
        ),
    ]
