# Generated by Django 3.2.4 on 2022-02-06 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0004_auto_20220110_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregistration',
            name='reg_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
