# Generated by Django 3.2.4 on 2022-02-06 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0005_alter_classregistration_reg_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregistration',
            name='reg_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
