# Generated by Django 3.2.4 on 2022-02-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0006_alter_classregistration_reg_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classregistration',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
