# Generated by Django 3.2.4 on 2022-05-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0008_classregistrationadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeginnerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('beginner', 'beginner'), ('returnee', 'returnee'), ('combined', 'combined')], max_length=20, null=True)),
                ('beginner_limit', models.IntegerField()),
                ('returnee_limit', models.IntegerField()),
                ('instructor_limit', models.IntegerField(default=10)),
                ('state', models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('full', 'full'), ('closed', 'closed'), ('canceled', 'canceled'), ('recorded', 'recorded')], max_length=20, null=True)),
                ('cost', models.IntegerField(default=5)),
                ('class_time', models.TimeField()),
                ('day_of_week', models.IntegerField(default=5)),
                ('frequency', models.IntegerField(default=1)),
                ('future_classes', models.IntegerField(default=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
