# Generated by Django 4.0.5 on 2022-08-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0009_beginnerschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnerclass',
            name='beginner_wait_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beginnerclass',
            name='returnee_wait_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beginnerschedule',
            name='beginner_wait_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beginnerschedule',
            name='returnee_wait_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beginnerclass',
            name='class_type',
            field=models.CharField(choices=[('beginner', 'beginner'), ('returnee', 'returnee'), ('combined', 'combined'), ('special', 'special')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beginnerclass',
            name='state',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('wait', 'wait'), ('full', 'full'), ('closed', 'closed'), ('canceled', 'canceled'), ('recorded', 'recorded')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beginnerschedule',
            name='class_type',
            field=models.CharField(choices=[('beginner', 'beginner'), ('returnee', 'returnee'), ('combined', 'combined'), ('special', 'special')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beginnerschedule',
            name='state',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('open', 'open'), ('wait', 'wait'), ('full', 'full'), ('closed', 'closed'), ('canceled', 'canceled'), ('recorded', 'recorded')], max_length=20, null=True),
        ),
    ]
