# Generated by Django 4.0.5 on 2022-11-29 01:28

from django.db import migrations, models
import django.db.models.deletion


def copy_event_data(apps, schema_editor):
    # copy the event data from the beginner class table to the event table
    bc = apps.get_model('program_app', 'BeginnerClass')
    event = apps.get_model('event', 'Event')

    for c in bc.objects.all().order_by('id'):
        c.event = event.objects.create(
            event_date=c.class_date,
            cost_standard=c.cost,
            cost_member=c.cost,
            state=c.state,
            type='class'
        )
        c.save()


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0002_event_type'),
        ('program_app', '0011_classregistration_modified_classregistration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnerclass',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.RunPython(copy_event_data),
    ]
