# Generated by Django 4.0.5 on 2022-12-01 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0012_beginnerclass_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beginnerclass',
            name='class_date',
        ),
        migrations.RemoveField(
            model_name='beginnerclass',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='beginnerclass',
            name='state',
        ),
    ]
