# Generated by Django 4.0.5 on 2023-01-04 16:23

from django.db import migrations


def copy_registration_data(apps, schema_editor):
    # copy the class registration admin data from the program_app.ClassRegistrationAdmin table to the event.Registration table

    cra = apps.get_model('program_app', 'ClassRegistrationAdmin')
    registration = apps.get_model('event', 'Registration')
    registration_admin = apps.get_model('event', 'RegistrationAdmin')

    for ra in cra.objects.all().order_by('id'):
        r = registration.objects.get(
            idempotency_key=ra.class_registration.idempotency_key,
            student=ra.class_registration.student
        )
        registration_admin.objects.create(
            class_registration=r,
            staff=ra.staff,
            note=ra.note
        )

class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0013_remove_beginnerclass_class_date_and_more'),
        ('event', '0005_registration_volunteerevent_registrationadmin')
    ]

    operations = [
        migrations.RunPython(copy_registration_data),
        migrations.RemoveField(
            model_name='classregistrationadmin',
            name='class_registration',
        ),
        migrations.RemoveField(
            model_name='classregistrationadmin',
            name='staff',
        ),
        migrations.DeleteModel(
            name='ClassRegistration',
        ),
        migrations.DeleteModel(
            name='ClassRegistrationAdmin',
        ),
    ]
