# Generated by Django 4.0.5 on 2023-05-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0014_remove_classregistrationadmin_class_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnerschedule',
            name='volunteer_points',
            field=models.IntegerField(default=2),
        ),
    ]
