# Generated by Django 4.2.1 on 2023-06-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0015_beginnerschedule_volunteer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnerschedule',
            name='week',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
