# Generated by Django 5.0.7 on 2025-02-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_app', '0016_beginnerschedule_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnerclass',
            name='staff_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='beginnerschedule',
            name='staff_limit',
            field=models.IntegerField(default=3),
        ),
    ]
