from .beginner_class_form import BeginnerClassForm
from .class_attendance_form import ClassAttendanceForm
from .class_registration_form import ClassRegistrationForm
from .student_form import StudentForm
from .student_registration_form import StudentRegistrationForm
from .student_search_forms import SearchEmailForm, SearchNameForm, SearchPhoneForm
